resources:
  jobs:
    training_job:
      name: "{{cookiecutter.lob_display_name}} - {{cookiecutter.project_slug}} Training Job"
      job_clusters:
        - job_cluster_key: default
          new_cluster:
            policy_id: ${var.cluster_policy_id}
            spark_version: ${var.spark_version}
            node_type_id: ${var.node_type_id}
            num_workers: 2
      tasks:
        # Classification training - delete if not needed
        - task_key: train_classification
          job_cluster_key: default
          spark_python_task:
            python_file: ../src/{{cookiecutter.project_slug}}/training/classification/train.py
            parameters:
              - "--catalog=${var.catalog}"
              - "--schema=${var.schema}"
              - "--model-name=${var.model_name}_classification"
              - "--experiment-path=${var.mlflow_experiment_path}/classification"

        # Time series training - delete if not needed
        - task_key: train_time_series
          job_cluster_key: default
          spark_python_task:
            python_file: ../src/{{cookiecutter.project_slug}}/training/time_series/train.py
            parameters:
              - "--catalog=${var.catalog}"
              - "--schema=${var.schema}"
              - "--model-name=${var.model_name}_time_series"
              - "--experiment-path=${var.mlflow_experiment_path}/time_series"

        # Clustering training - delete if not needed
        - task_key: train_clustering
          job_cluster_key: default
          spark_python_task:
            python_file: ../src/{{cookiecutter.project_slug}}/training/clustering/train.py
            parameters:
              - "--catalog=${var.catalog}"
              - "--schema=${var.schema}"
              - "--model-name=${var.model_name}_clustering"
              - "--experiment-path=${var.mlflow_experiment_path}/clustering"

        # Evaluation - runs after all training tasks